openapi: 3.1.0
info:
  title: Divination
  description: |-
    This is a Web API for fetching rules text from Magic: The Gathering's comprehensive rules.
  version: 0.0.1
servers:
  - url: https://divination.cardspy.nz
tags:
  - name: rules
    description: Fetch operations on the MTG Comprehensive Rules
paths:
  /divination/rules/{index}:
    get:
      tags:
        - rules
      summary: Find a single rule
      description: Retrieves a single MTG rule based on the index
      operationId: findRuleByIndex
      parameters:
        - name: index
          in: path
          description: Index of MTG rule
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rule'
        '400':
          description: No index provided
        '404':
          description: No rule found for the given index
  /divination/rules/search:
    get:
      tags:
        - rules
      summary: Query the rule database
      description: Finds rules based on a provided search query
      operationId: queryRules
      parameters:
        - name: query
          in: query
          description: Text to search rules by
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rule'
        '400':
          description: No query provided
        '404':
          description: No rule found for the given query
components:
  schemas:
    Rule:
      type: object
      properties:
        index:
          type: string
          examples: ["104.3a", "104.3b"]
        description:
          type: string
          examples: ["A player can concede the game at any time. A player who concedes leaves the game immediately. That player loses the game.", "If a player’s life total is 0 or less, that player loses the game the next time a player would receive priority. (This is a state-based action. See rule 704.)"]
