name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - 'LICENSE'
      - '.idea/**'

jobs:
  publish:
    name: Publish latest Docker image to registry
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/divination-api

  dispatch:
    name: Trigger redeploy on CD pipeline
    runs-on: ubuntu-latest
    needs: publish

    env:
      APP_NAME: 'divination.nz'
      POD_NAME: 'divination-api'

    steps:
      - name: Dispatch CI event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ secrets.TARGET_REPO }}
          event-type: ci-dispatch
          client-payload: '{"ref": "${{ github.ref }}", "repository": "${{ github.repository }}", "app": "${{ env.APP_NAME }}", "pod": "${{ env.POD_NAME }}"}'
